apiVersion: v1
kind: Service
metadata:
  name: {{ include "ots.fullname" . }}
  labels:
    {{- include "ots.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7143
      protocol: TCP
      name: http
  selector:
    {{- include "ots.selectorLabels" . | nindent 4 }}
